server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    username: 'mike'
    url: jdbc:postgresql://localhost:5432/customer
    password: 'password'
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL9Dialect
          format_sql: 'true'
      hibernate:
        ddl-auto: update
      show-sql: true
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: update

