server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    username: 'mike'
    url: jdbc:postgresql://localhost:5432/fraud
    password: 'password'
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL9Dialect
          format_sql: 'true'
      hibernate:
        ddl-auto: update
      show-sql: true
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true
      show-sql: true